env:
  browser: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  project: ["./tsconfig.json"]
  ecmaVersion: 6
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {}
ignorePatterns: ["packages/**/*.d.ts", "packages/**/*.js"]
