
install:
	yarn install

build:
	yarn build

build-types:
	cd packages/types && yarn gen && yarn build

build-utils:
	cd packages/utils && yarn build

build-oraclesetup:
	cd packages/oraclesetup && yarn gen && yarn build

compile:
	yarn build:compile

lint:
	yarn lint

oracle-setup:
	cd packages/oraclesetup && yarn && yarn start
